.TH "adctemp.h" 3 "Thu Nov 13 2014" "Version 1.0" "ATmega328p Thermometer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adctemp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/pgmspace\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ATmega328p Thermometer from the source code\&.
